### ISSUE TITLE
RAML Changes -- Support-Logging master branch

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#56]
The following PR in the edgex-go master branch contains changes to the RAML which I'm sure will impact blackbox tests.

https://github.com/edgexfoundry/edgex-go/pull/423

We'll need changes to the support-logging tests in the master branch and how they handle/check status codes according to this new RAML. Once the test definitions have been updated, please assign @brandonforster for verification.

This is the first of many PRs for this effort.

**Comment by cloudxxx8** [comment]
fixed by #84 and #85 
we have verified all the blackbox can be passed in delhi
@brandonforster could you please help confirm on your side and close this issue?
Thanks

**Comment by brandonforster** [comment]
Please find attached a few test logs. I noticed these failures on the testing master branch and with the corresponding data files. I changed the URL of the tests from {SERVICE_NAME}:{port} to localhost:{port} but otherwise they are as presented in the repo.


[logs.postman_test_run.json.txt](https://github.com/edgexfoundry/blackbox-testing/files/2566434/logs.postman_test_run.json.txt)
[support-notifications.postman_test_run.json.txt](https://github.com/edgexfoundry/blackbox-testing/files/2566435/support-notifications.postman_test_run.json.txt)
[device.postman_test_run.json.txt](https://github.com/edgexfoundry/blackbox-testing/files/2566436/device.postman_test_run.json.txt)

**Comment by cloudxxx8** [comment]
@brandonforster 
Please verify it on delhi branch for now, because we are making some changes on master.  delhi branch is the stable one.
Also, may we confirm your test execution steps?  It looks like the test data had not been imported into the database.

**Comment by brandonforster** [comment]
@cloudxxx8 I am executing these on delhi.

I am selecting the test collection, selecting the appropriate environment, changing the environment's URL that doesn't resolve (usually "edgex-core-url") to "localhost", choosing the appropriate data package, and then running the tests. If there are more instructions or something I'm missing, please, provide them but might I recommend also including whatever instructions I'm missing on the main README because it is tremendously hard to figure out what to be doing with these without asking anyone else.

**Comment by cloudxxx8** [comment]
@brandonforster 
In the README, we have pointed out the instruction located in the docs folder
https://github.com/edgexfoundry/blackbox-testing/tree/master/docs
Please take a look and let me know if you encounter further issues.  Thanks

**Comment by brandonforster** [comment]
This is what I was looking for, thank you so much.

I'll redo it following the instructions and let you know.

**Comment by brandonforster** [comment]
@cloudxxx8 Sorry about the delay, I had some other things going on I needed to manage. The newman instruction were excellent; thanks for doing that Trevor and thanks for pointing me in the direction of them.

Everything worked great except `core-command`. I checked out the `delhi` branch, checked out master for `blackbox-testing` pulled latest changes on both and got the errors attached.
[error.txt](https://github.com/edgexfoundry/blackbox-testing/files/2587205/error.txt)

**Comment by cloudxxx8** [comment]
@brandonforster 
As I mentioned the `master` branch of balckbox-testing is modifying, could you please try it on the `delhi` branch of blackbox-testing?
Also, I would like to close this issue for now, because this issue is related to support-logging and everything in support-logging works fine now.
We could discuss the error you encountered via email, if it still happens in `delhi` branch of blackbox-testing.
Thanks for your verification.
